name: Build and push Docker images

on:
  push:
    branches: [ "init" ]
  pull_request:
    branches: [ "init" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.5.0
