name: Docker Image CI

on:
  push:
    branches: [ "init" ]
  pull_request:
    branches: [ "init" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag azuli-robot:$(date +%s)
